-- load data to expense category item table

insert into mhet_expense_category_item values ('Home Provision', 'Home Provision',null);
insert into mhet_expense_category_item values ('Fruits', 'Fruits',null);
insert into mhet_expense_category_item values ('Vegetables', 'Vegetables',null);
insert into mhet_expense_category_item values ('Cookies/Snacks','Cookies/Snacks, etc.',null);
insert into mhet_expense_category_item values ('Restaurant','Restaurant Food',null);
insert into mhet_expense_category_item values ('Entertainment','Movie Ticket, DVD/Bluray, etc.',null);
insert into mhet_expense_category_item values ('Cosmetics','Cosmetics items',null);
insert into mhet_expense_category_item values ('Bathroom Cleaning','Bathroom cleaing items',null);
insert into mhet_expense_category_item values ('Kitchen Items','Kitchen items',null);
insert into mhet_expense_category_item values ('Non-Veg','Mutton, Chicken,Fish,Prawn',null);
insert into mhet_expense_category_item values ('Happy Hours','Happy Hours/Weekend Party',null);
insert into mhet_expense_category_item values ('Travel','Taxifare',null);
insert into mhet_expense_category_item values ('Travel','Autofare',null);
insert into mhet_expense_category_item values ('Travel','Busfare',null);
insert into mhet_expense_category_item values ('Travel','Airfare',null);
insert into mhet_expense_category_item values ('Travel','Trainfare',null);
insert into mhet_expense_category_item values ('Dress','Dress shopping',null);
insert into mhet_expense_category_item values ('Books','Books',null);
insert into mhet_expense_category_item values ('School Fees','School Fees & other charges',null);
insert into mhet_expense_category_item values ('Maintenance','Two-Wheeler Maintenance',null);
insert into mhet_expense_category_item values ('Maintenance','Two-Wheeler Petrol',null);
insert into mhet_expense_category_item values ('Maintenance','Two-Wheeler Service/Repair',null);
insert into mhet_expense_category_item values ('Maintenance','Car Maintenance',null);
insert into mhet_expense_category_item values ('Maintenance','Car Petrol/Diesel',null);
insert into mhet_expense_category_item values ('Maintenance','Car Service/Repair',null);
insert into mhet_expense_category_item values ('Maintenance','Apartment Charges',null);
insert into mhet_expense_category_item values ('Medicines','Tablets, Syrup, etc.',null);
insert into mhet_expense_category_item values ('Utility Bills','Telephone Landline',null);
insert into mhet_expense_category_item values ('Utility Bills','Mobile',null);
insert into mhet_expense_category_item values ('Utility Bills','Wi-Fi',null);
insert into mhet_expense_category_item values ('Utility Bills','Data Card',null);
insert into mhet_expense_category_item values ('Utility Bills','Electricity',null);
insert into mhet_expense_category_item values ('Utility Bills','Gas',null);
insert into mhet_expense_category_item values ('Utility Bills','Water',null);
insert into mhet_expense_category_item values ('Utility Bills','TV Cable/DTH Bills',null);
insert into mhet_expense_category_item values ('Utility Bills','Sewer',null);
insert into mhet_expense_category_item values ('Credit Card Bills','Standard Chartered XXXX',null);
insert into mhet_expense_category_item values ('Money Transfer','Money Transferred to someone',null);
insert into mhet_expense_category_item values ('Salary','Maid',null);
insert into mhet_expense_category_item values ('Salary','Cook',null);
insert into mhet_expense_category_item values ('Salary','Nanny',null);
insert into mhet_expense_category_item values ('Salary','Car Cleaner',null);
insert into mhet_expense_category_item values ('Miscellaneous','Misc. Expenses',null);
insert into mhet_expense_category_item values ('Loan Payment','Principal',null);
insert into mhet_expense_category_item values ('Loan Payment','Interest',null);
insert into mhet_expense_category_item values ('Installment','Installment Paid',null);
insert into mhet_expense_category_item values ('Toll Recharge','Toll Recharge',null);
insert into mhet_expense_category_item values ('Chit Fund','Chit Fund, Gold Chit Payment',null);
insert into mhet_expense_category_item values ('Fitness/Gym','Fitness/Gym Payment',null);
insert into mhet_expense_category_item values ('Hospital Expenses','Regular Checkup',null);
insert into mhet_expense_category_item values ('Hospital Expenses','Consultation Charges',null);
insert into mhet_expense_category_item values ('Hospital Expenses','Treatment',null);
insert into mhet_expense_category_item values ('Insurance','Vehicle Insurance',null);
insert into mhet_expense_category_item values ('Insurance','Health Insurance',null);
insert into mhet_expense_category_item values ('Insurance','Mediclaim',null);
insert into mhet_expense_category_item values ('Party Expense','Kitty, Birthday, Other Occasions',null);
insert into mhet_expense_category_item values ('Shopping','Shopping',null);
