-- Populate data into expense category table

insert into mhet_expense_category values ('Home Provision', 'Provisions to be bought such as rice, dal, cooking ingredients, etc.');
insert into mhet_expense_category values ('Fruits', 'Apple, Orange, Grapes, Gova, etc.');
insert into mhet_expense_category values ('Vegetables', 'All kind of vegitables');
insert into mhet_expense_category values ('Cookies/Snacks','Cookies/Snacks, etc.');
insert into mhet_expense_category values ('Desserts','Ice creams, etc.');
insert into mhet_expense_category values ('Restaurant','Hotel brakfast,lunch, dinner, snacks');
insert into mhet_expense_category values ('Entertainment','Movie Ticket, DVD/Bluray, etc.');
insert into mhet_expense_category values ('Cosmetics','All cosmetics items');
insert into mhet_expense_category values ('Bathroom Cleaning','Bathroom cleaing items (liquid, saop, broom, etc.');
insert into mhet_expense_category values ('Kitchen Items','Kitchen items such as kitchen knife,etc.');
insert into mhet_expense_category values ('Non-Veg','Mutton, Chicken,Fish,Prawn');
insert into mhet_expense_category values ('Starters','Munchurians, etc.');
insert into mhet_expense_category values ('Chips','Chips');
insert into mhet_expense_category values ('Happy Hours','Happy Hours, Friend outings, Friday Outing, Weekday Outing, Weekend Outing');
insert into mhet_expense_category values ('Travel','Taxifare, Autofare, Busfare, Airfare, Trainfare');
insert into mhet_expense_category values ('Edible Oil','Cooking oils - Cocunut,Gingerly, Sasme,etc.');
insert into mhet_expense_category values ('Dress','Family Head, Home Maker, Daughter, Son, Guest, Friend, Relative');
insert into mhet_expense_category values ('Books','Study releated, leisure reading');
insert into mhet_expense_category values ('School Fees','Daughter, Son');
insert into mhet_expense_category values ('School Other Fees','Daughter, Son');
insert into mhet_expense_category values ('Car Maintenance','Petrol, Maintenance & Service');
insert into mhet_expense_category values ('Two-Wheeler Maintenance','Petrol, Maintenance & Service');
insert into mhet_expense_category values ('Medicines','Tablets, Syrup, etc.');
insert into mhet_expense_category values ('Utility Bills','Telephone Landline, Mobile, Wi-Fi, Data Card, Electricity, Gas, Water, Sewer, TV Cable/DTH Bills');
insert into mhet_expense_category values ('Credit Card Bills','Credit Card Bill Payment');
insert into mhet_expense_category values ('Money Transfer','Money Transferred to someone');
insert into mhet_expense_category values ('Salary','Salary paid to Maid, Servant, Cook, Nanny');
insert into mhet_expense_category values ('Miscellaneous','Miscellaneous Expenses that doesn''t come under any of expense category');
insert into mhet_expense_category values ('Loan Payment','Principal, Interest, Late Charges Amount');
insert into mhet_expense_category values ('Installment','Installment Paid');
insert into mhet_expense_category values ('Toll Recharge','Toll Recharge');
insert into mhet_expense_category values ('Chit Fund','Chit Fund, Gold Chit Payment');
insert into mhet_expense_category values ('Fitness/Gym','Fitness/Gym Payment');
insert into mhet_expense_category values ('Apartment Maintenance','Apartment/Community Maintenance Payment');
insert into mhet_expense_category values ('Hospital Expenses','Fitness/Gym Payment');
insert into mhet_expense_category values ('Insurance','Vehicle Insurance, Life Insurance, Health & Mediclaim Insurance Policy');
insert into mhet_expense_category values ('Party Expense','Kitty Party, Birthday Party, Other Occasion Party');
insert into mhet_expense_category values ('Maintenance','All Maintenance');
insert into mhet_expense_category values ('Shopping','Shopping');
